### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by mxstbr** [css-components/styled-components#7]
Currently, doing this won't work (React throws an error that you have to return an element, null or etc.):

```JS
const Component = (props) => {
  return styled.div`
    background-color: ${props.bg};
  `;
}
```

You have to do this to make it work:

```JS
const Component = (props) => {
  const Primitive = styled.div`
    background-color: ${props.bg};
  `;
  return <Primitive />;
}
```

Which seems unnecessary, verbose and confusing. I'm not sure if we can do something against this though?

**Comment by geelen** [comment]
I missed this. This is awful. Let's fix this.

**Comment by geelen** [comment]
Ok so given we _must_ return a component (because we can't pass props to the rendered element if we don't, see #19), we need another way to conditionally apply styles.

This works but is ugly:

```js
const A = props => styled.div`
  color: ${props.color || 'black'};
`(props)
```

Because ``` styled.div`` ``` returns `props => createElement()` you can call it directly passing the props onwards and it's all ok. But it looks horrible.

We could make this work too:

```
const A = styled.div(props => `
  color: ${props.color || 'black'};
`)
```

Except now we don't have a tagged template literal to work with. So if we want to use anything advanced with the interpolations we'd have to do ``styled.div(props => css`...`)``. I'm still not convinced that we should go down the all-strings-all-the-time route.

So we need a better way of doing conditional styles from props.

**Comment by geelen** [comment]
This is a better way to do conditionals: https://github.com/css-components/styled-components/pull/24
